### ISSUE TITLE
RefineNet

### ISSUE THREAD

**Issue by arsalanshakeel** [JunkyByte/deepcharuco#1]
Hey @JunkyByte, 

Thanks for the deepcharuco implementation. To my understanding, considering the diagram and the model architecture that the authors have defined in the research paper, it seems like the model architecture of CharUcoNet and RefineNet is the same except for the last heads (CharUcoNet 2-headed output and RefineNet 1-head output), What I mean is in total 8 convolutions and 3 max-pool layers, each max-pool after 2 consecutive convolution layers. 

I would like to know that for the RefineNet model architecture, you have opted for upsampling. Was there any particular reason or am I missing out on something? please enlighten me.

**Comment by JunkyByte** [comment]
Hi @arsalanshakeel thanks for your interest.

I have opted for upsampling because the architecture they presented for RefineNet is not clear to me.

Yes it seems that the architecture should be the same up to the heads, but if you input a (24,24) patch into that VGG based backbone you have a (C, 24/8, 24/8) output from the last conv.
How the head should be designed to output a 4096D vector starting from this (C, 3, 3) is a mystery to me.

That's why I opted for upsampling:
I remove some border pixels using padding=0 in the first few convs to obtain a (C, 16, 16) tensor. I apply max pool to (C, 8, 8) and continue by 2x upsampling 3 times to obtain a (1, 64, 64) as output.

If you have a valid idea on how to design the RefineNet feel free to discuss it
